### ISSUE TITLE
detect if mac and disable / gray out "sample start sample end stuff"

### ISSUE THREAD

**Issue by esaruoho** [vsariola/sointu#10]
there's some materials that are only available for pc, i.e. wavetable playback or something like that. gray it out on mac?

**Comment by vsariola** [comment]
The sample start / loopstart stuff / loopend currently only show up when the oscillator type is "Sample"; I would prefer one to be able to edit song files at any platform even though one cannot here any sound from samples (which are Windows only). Is this a major issue, to be able to edit them? Perhaps a warning note "(!) Samples (gm.dls) are only supported on Windows" should appear below the sliders?

**Comment by esaruoho** [comment]
Warning sounds good:)

**Comment by esaruoho** [comment]
closing
