### ISSUE TITLE
Invalid YML is saved directly after deleting units

### ISSUE THREAD

**Issue by LeStahL** [vsariola/sointu#103]
Directly after deleting units, a syntactically wrong yaml file is saved when hitting CTRL+s.

It contains all the relevant information, but also extra parts at random places.

**Comment by LeStahL** [comment]
For example: [bug.zip](https://github.com/vsariola/sointu/files/12501354/bug.zip)

**Comment by vsariola** [comment]
I hate os.OpenFile, how can it be so hard to get this thing right :D The file was not truncated while opened for writing. Fixed.
