### ISSUE TITLE
Cross-Instrument Modulation Mechanism

### ISSUE THREAD

**Issue by LeStahL** [vsariola/sointu#107]
Same-instrument modulation behaves differently from cross-instrument modulation - this is a discussion ticket and also a point of reference for the workflow with parameter modulation from the global instrument.

Situation: When using a "send" unit that targets 
* the same instrument, by default, all voices of the instrument will be modulated - or the exact voice selected by the "voice" parameter in the "send" unit.
* a different instrument, only the first voice of the target instrument will be modulated by default (respecting stereo), or the exact voice selected by the "voice" parameter in the send unit.

A discussion with @vsariola reveiled that this is by design, and the intended workflow for cross-instrument modulation is
to create a modulation unit followed by as many "send" units as the target instrument's voice count (the first "send" unit without sendpop, the last one with sendpop enabled).

**Comment by vsariola** [comment]
Slight correction: the situation currently is that every send always just modulates one voice. If you want to modulate an instrument with multiple voices, let's say three, you need three different SENDs.

The meaning of "auto":
- If the unit is within the same instrument, the modulation targets always "self" i.e. if this is the voice 0 of the instrument, that modulation would target voice 0. Similarly, if this is voice 1 of a multivoice instrument, "auto" modulation modulates a unit in voice 1.
- The meaning of "auto" is confusing when cross-modulating, as it actually just modulates voice 0 of another instrument.

Proposed fix:
- For self-modulating instruments, rename "auto" to "self" to make it more clear that this means "the voice itself"
- Give new meaning for "auto" in the cross-modulating instruments: "all". "all" would mean that all the voices are modulated; this would be implented by compiling the send to multiple units.

I don't think there's no use case for self-modulating "all", as it likely would lead to weird behavior anyway. However, it is still possible to implement that manually, just by chaining N sends, where N is the number of voices.

**Comment by vsariola** [comment]
Ok, there's a catch though, which is minor: if we actually compile a send unit into multiple sends, then if an another send is modulating this send only targets the first. But send modulating send is such a rare occurrence that maybe this is not an issue.

**Comment by vsariola** [comment]
Can you try the quick test in feat/all-modulation branch if it would've worked for what you were trying to do?

**Comment by LeStahL** [comment]
Yes, this is exactly what I tried to do :) thanks!

**Comment by LeStahL** [comment]
Also: The old variant still works.

**Comment by vsariola** [comment]
Merged, enjoy!
