### ISSUE TITLE
macosx file open dialog broken

### ISSUE THREAD

**Issue by m0ppers** [vsariola/sointu#110]
on macosx (intel, sonoma) when trying to open any file explorer (open, save) the whole tracker stops responding and the file explorer will never open. I tried upgrading to latest gioui/x but that didn't help. probably an upstream issue but not sure. I am not a real go developer.

**Comment by vsariola** [comment]
Yeah, I had issues using the OS-specific file dialogs in the past, and wrote my custom widgets for the file explorers. However, maintaining those custom file explorers was becoming a pain and they had several issues too, so I hopefully jumped back to using gioui/x explorers. I see that there still some issues with that :)

Anyway, to be able to do something right now, I suggest try copy-pasteing the file to Sointu. It should unmarshal the song data from the clipboard. Similarly, to save data, you can copy-paste stuff from sointu to a text file. Internally, sointu marshals all data to clipboard as yaml files.

I don't have mac, so I may need your help at some point to verify if various fix attempts solve this issue.

**Comment by m0ppers** [comment]
omg. didn't know about the copy-paste workaround. that might just do it for now :heart: I personally also don't have immediate access a mac. I helped a friend to get going. but I meet him frequently. so I should be able to help a bit

**Comment by vsariola** [comment]
I have pushed a new commit that might solve the issue with file dialogs. Can you @m0ppers or someone else with a mac test?

**Comment by themusicjinn** [comment]
works on MacOs Sonoma (Intel chip) 🎉  thanks

**Comment by vsariola** [comment]
Cool! Thanks for testing. Closing.
