### ISSUE TITLE
Mouse wheel on faders is inverted

### ISSUE THREAD

**Issue by wayfu** [vsariola/sointu#112]
Currently, scrolling up decreases the value, and vice versa. Should be the other way 'round!

**Comment by vsariola** [comment]
Yeah, it should be. When putting it the way it is, I kind imagined how it would feel if the wheel is knob, but it's true that up = larger is the usual logical way it should be.

I'll flip them once I have my GUI rewrite/refactoring merged to the master.

**Comment by vsariola** [comment]
It was as hard as adding one minus sign :D The changelog message was longer than the actual change...

**Comment by wayfu** [comment]
now the mouse wheel does not appear to work at all...?

**Comment by vsariola** [comment]
The mousewheel was changed

**Comment by wayfu** [comment]
ah! i did not even realize that parameters could even be selected. perhaps clicking the control and adjusting the parameter should also select it, and not just clicking the name?
