### ISSUE TITLE
Typing in the text fields plays notes

### ISSUE THREAD

**Issue by wayfu** [vsariola/sointu#113]
... when you type a letter that's part of the computer keyboard based virtual midi keyboard.

**Comment by vsariola** [comment]
Good that you opened an issue, I knew this was there but since it was just a annoying thing, it was not a priority :) Will fix once I understand how to prevent events from flowing through the input field, I just couldn't figure out an easy way to do it in Gio yet (the GUI library used).

**Comment by vsariola** [comment]
I believe this should be working now, let's reopen if I didn't manage to prevent all events from flowing through.
