### ISSUE TITLE
Comment per op

### ISSUE THREAD

**Issue by wayfu** [vsariola/sointu#114]
one of the most difficult things to keep track of when things get complicated is which op does what. it would be cool there wasn't only the per-instrument comment but also per-op comments.

**Comment by vsariola** [comment]
This is not a bad idea. Maybe not multi-line comment field, but more like a single line comment / name for the unit. This would also make it easier to target modulations, as we can show the name of the unit, not just the index and type.

**Comment by LeStahL** [comment]
Maybe it would also be cool to save those comments as actual comments in the yaml file (I'm not sure of the yaml parser used is capable of parsing comments, but it would make complete sense to me to have comments above stuff show up as comments in the tracker ui :)
