### ISSUE TITLE
Bypass op

### ISSUE THREAD

**Issue by wayfu** [vsariola/sointu#116]
it would be nice if it were possible to temporarily disable ops in the gui, without losing all the settings

**Comment by vsariola** [comment]
So many good suggestions! Yes, this would be a great feature. With the upcoming ability to easily select multiple units, it would be great to disable them all at once.

**Comment by LeStahL** [comment]
Maybe this could be in the yaml as well ("Commented ops are bypassed")? That's relevant extra parsing effort, but would be feel kind of "natural"

**Comment by LeStahL** [comment]
Bypassing could be activated when pressing "CTRL+D" while having units selected, and deactivated with CTRL+SHIFT+D.

**Comment by vsariola** [comment]
I'll just make a boolean named disabled for each unit and falses are not exported so it's fully compatible with current tracks. The yaml parser / serializer is pretty rigid; better not waste time trying to hack it.

**Comment by vsariola** [comment]
Ok, Ctrl-D disables/re-enables the currently selected unit(s). This are marked in the yaml as `disabled: true`. The disabled units are considered non-existent when compiling the patch. The disable units are displayed in gray and italic:
![image](https://github.com/vsariola/sointu/assets/5684185/b89fc577-755d-4e60-b18d-078b4a3b196a)
