### ISSUE TITLE
Set, Mul & Add modes for send

### ISSUE THREAD

**Issue by wayfu** [vsariola/sointu#117]
sometimes you want more than one send to influence the same value. it would be good to have Set, Mul, and Add mode available so that effects from multiple sources can be combined

**Comment by vsariola** [comment]
SET would be redundant, as multiple sends targeting the same value already work like an "ADD". The port is reset to 0 every cycle so sends A and B targeting a port works like: calculate 0 + A + B, then add this to the modulated value.

This is pretty deep design choice in Sointu and is unlikely to change. Internally, SEND unit is already out of bit fields for flags (it uses all 16 bits it has already for it's data), so adding one more bit for "MUL" / "ADD" would require 17th bit i.e. adding new byte to the data of SEND.

Also, two sends with "MUL" set as its mode would not work quite as one would expect, as all ports are reset to 0 during one cycle so it would 0 * A * B = always 0

Can you give a specific example where Mul is needed? I think it's a pretty specific, rare use case, and there's a way to implement it using RECEIVE-RECEIVE-MULP or something like that.
