### ISSUE TITLE
Host virtual keyboard vs. sointu virtual keyboard

### ISSUE THREAD

**Issue by wayfu** [vsariola/sointu#119]
I am working in Ableton Live, and its virtual keyboard is single octave on the middle and top row (AWSEDFTGZHUJKOL). sointu has its own virtual keyboard with a different layout. even already held keys will switch to whatever interpretation when you change focus, leading to confusion when trying to dial in sounds while playing them. it would be good if there were a way to perhaps set sointu into "vsti mode" and disable the tracker features, including the virtual keyboard.

**Comment by vsariola** [comment]
Firstly, nice to hear that sointu works with Ableton :) Second, this in principle easy to implement, but I am not sure how useful it really is. The two-octave layout is mainly for the internal tracker, and I recall we historically aped it from existing trackers. It's pretty close to Renoise at least. The VSTI side of sointu is more recent, so that's why.

**Comment by vsariola** [comment]
Question: Now that the latest master allows the user to redefine all the keybindings, in [keybindings.yml](https://raw.githubusercontent.com/vsariola/sointu/refs/heads/master/tracker/gioui/keybindings.yml) which is located in the Sointu configuration directory (`os.UserConfigDir()/sointu/keybindings.yml`), is that enough to solve this issue?

In your case, you could for example:
a) Delete the NoteXXX binding altogether (probably bad idea)
b) Make only one octave of the note bindings, so it matches Ableton exactly
c) Add something like "alt: true" to all the note bindings, so you need to hold alt to trigger the notes

**Comment by vsariola** [comment]
I'm closing this as I believe this is best solved by the user define his / her own keybindings, if the default ones are not satisfactory.

**Comment by vsariola** [comment]
Still a little change: the user-defined keybindings.yml just documents *changes* from the default keybindings.yml. So, if swapping A <-> Z is the only thing you need, you can define just those two lines and let the default keybindings.yml define all the rest. A line with no `action:` means "unbind" the key.
