### ISSUE TITLE
File ->"Open song" crashes on Mac

### ISSUE THREAD

**Issue by esaruoho** [vsariola/sointu#12]
could folder or open be made to work with macOS Big Sur ?:)

**Comment by vsariola** [comment]
Well, having no file open is not a long term solution. I'll rather try to keep on looking for a solution to fix it; might have to fork some open source golang dialog project and fix the dialogs myself.

**Comment by esaruoho** [comment]
changed ticket to be about no longer crashing if clicking on folder or save or open

**Comment by esaruoho** [comment]
still crashes on clicking Open Song, unfortunately

**Comment by vsariola** [comment]
I just pushed a version with completely self-implemented save/load dialogs; hopefully they work better than the "cross-platform" dialog library I was using previously.
