### ISSUE TITLE
the dropdown for targeting sends can make it impossible to choose certain ops

### ISSUE THREAD

**Issue by wayfu** [vsariola/sointu#121]
on targets with a lot of ops, the list can be longer than the sointu window is tall, but there's no way to scroll it, and it doesn't wrap or reposition itself to make everything visible, so if that list is too long, the later ops become inaccessible

**Comment by vsariola** [comment]
This should be an easy fix, I think there actually is an scrollbar, but it appears "too late" i.e. it doesn't actually detect how much there's space for the widget, but only starts to scroll when the number of items is enough. There is a deep reason for this, which is related to how Gio handles layouts: widget does not get information about where it is located relatively to window edges, only where it is located to latest clipping area, and afaik this hasn't changed, so the solution may be just to make the dropdown small enough that it will fit on screen in the typical window size people typically use with sointu.
