### ISSUE TITLE
Warn user about samplerate being other than 44100 (was: Recording seems to skip steps)

### ISSUE THREAD

**Issue by MartiniMoe** [vsariola/sointu#129]
![image](https://github.com/vsariola/sointu/assets/7438779/7d97c342-5e13-4c9d-8175-5e992c8a7255)

On the left you can see my track in Renoise. On the right is Sointu after recording the notes from renoise. As you can see there is a skipped empty step at 05/06. This repeats on steps 12/13, 1F/20 and so on.

Any idea what is causing this?

**Comment by vsariola** [comment]
Maybe Sointu doesn't get BPM from host correctly? Try setting BPM manually to correct before recording. Alternatively, there is some rounding issue with the rounding of MIDI events frames to row numbers. I'll investigate

**Comment by vsariola** [comment]
So things go wrong somehow here: https://github.com/vsariola/sointu/blob/c08a319eb793ab6eb24d1b3c83de2c8b9dd4c159/tracker/recording.go#L142

**Comment by vsariola** [comment]
I don't know how Renoise does BPM changes but if the BPM doesn't stay constant for some reason, it could explain

**Comment by vsariola** [comment]
Maybe you are at 48000 samplerate, while Sointu assumes fixed 44100?

**Comment by MartiniMoe** [comment]
> Maybe you are at 48000 samplerate, while Sointu assumes fixed 44100?

Ah, that was it! :tada: 

I'm using pipewire and running `pw-metadata -n settings 0 clock.force-rate 44100` fixed this for me! Thank a lot :)

**Comment by vsariola** [comment]
I'll make this into a feature request: warn user about wrong samplerate & document the requirement for 44100. Granted, in the year 2024, that number could be 48000. But there's historical baggage here.

**Comment by vsariola** [comment]
Nice to hear you are able to compile & run the VSTI on Linux :)

**Comment by vsariola** [comment]
This should get the job done: 
![image](https://github.com/vsariola/sointu/assets/5684185/6d8d415f-6108-4dea-a828-a7b78d9f72ad)
