### ISSUE TITLE
Copy&Paste of units doesn't assign a new id

### ISSUE THREAD

**Issue by kebby** [vsariola/sointu#138]
When you c&p a unit the new unit has the same id as the copied one. This breaks as soon as you try to use sends to the new unit - they all arrive at the previous one (the UI also reflects that).

Please assign a new id to units when pasting.

**Comment by vsariola** [comment]
This is probably a result of the complete refactoring / rewrite of the model of the GUI, sorry! Investigating.

**Comment by vsariola** [comment]
Actually, probably vice versa: this was fixed by the big refactoring / rewrite, and you are probably still on 0.3.0, correct?

**Comment by kebby** [comment]
Seems fixed in the latest version, thanks!
