### ISSUE TITLE
F1 to Order List, F2 to Tracker, F5 to playback, f8 to stop

### ISSUE THREAD

**Issue by esaruoho** [vsariola/sointu#14]
map F1 to Order list, F2 to Tracker, F5 to Playback, F8 to stop

**Comment by vsariola** [comment]
Is it good now? F5 plays, F6 plays with notetracking off, F7 continues to play where it previously was, F8 stops. F1-F4 are different edit modse

**Comment by esaruoho** [comment]
works, closing
