### ISSUE TITLE
Better testing of the Disabled flag.

### ISSUE THREAD

**Issue by vsariola** [vsariola/sointu#140]
In #139, a bug was discovered in the Disabled flag. The original sin was that the feature was added hastily without proper testing.

This issue is here just to remind to add proper unit tests for the unit Disabled flag, to see that there are no further lurking bugs in there.

The feature could also be reimplemented in a more future-proof way: just filter out all the disabled units before generating the bytecode so there is no way the disabled units could affect the compile results.

**Comment by LeStahL** [comment]
https://github.com/vsariola/sointu/blob/master/vm/delaytable.go#L145-L147

this block seems to crash the tracker now if a track with disabled units is in the cache.

**Comment by LeStahL** [comment]
Don't worry. :) shit happens. Also you're always really quick with the maintenance here, which is super cool imo :)

**Comment by vsariola** [comment]
Took me while to figure out how to make the crash, but the immediate fix to the crash & the unit tests should be there.

**Comment by vsariola** [comment]
I didn't do the refactoring to filter out the disabled units, because that would make a slightly unnecessary copy of the synth structure just for that purpose; this is something that happens every time you e.g. move a slider a notch so I'm a bit worried that maybe the amount garbage this creates is not negligible... so I need to test this in real action if there's any effect on performance.
