### ISSUE TITLE
error message overlays controls

### ISSUE THREAD

**Issue by wayfu** [vsariola/sointu#142]
when a unit leaves voices on the stack, the error messages overlays the delete unit button (and some other stuff)

**Comment by vsariola** [comment]
Can you paste a screenshot? Or I assume that you are working on a small screen size or window size, but I'm curious what's you "preferred" screen size to work on, so I can get an idea how small people go.

**Comment by wayfu** [comment]
this is just on the default width! i usually like the window tall rather than wide, since i only use the synth and not the tracker.

![image](https://github.com/user-attachments/assets/b85da3fb-8bdb-4730-8112-f6c3543d57e7)

**Comment by vsariola** [comment]
I moved the alerts slightly up so they don't overlay the buttons.
