### ISSUE TITLE
Setting cursor step in tracker UI does not currently do anything

### ISSUE THREAD

**Issue by bsh-hub** [vsariola/sointu#144]
Setting cursor step in tracker UI does not have effect.

![image](https://github.com/user-attachments/assets/4435d3cc-4392-4a53-a518-d356eb5e8d04)

Tested with build: https://github.com/vsariola/sointu/actions/runs/10502605949

**Comment by vsariola** [comment]
Confirmed. Oops. Fix should be easy fortunately.
