### ISSUE TITLE
Indicate that tracker UI sections are resizable

### ISSUE THREAD

**Issue by bsh-hub** [vsariola/sointu#145]
It would be nice to have some kind of UI indication (see example from picture) that the sections in the tracker interface are resizable. 

I did not know that. But I noticed that I can drag the "black lines" when creating this issue. So actually quite unimportant thing because the sections already are resizable.

![image](https://github.com/user-attachments/assets/7cfb8555-324d-4a94-90b2-c42ae393deb0)

**Comment by vsariola** [comment]
There used to be a different cursor indicating it, but I need to check that it still works after migrating to latest Gioui version (the GUI library I use).

**Comment by vsariola** [comment]
Done. I am pretty sure that I had this cursor indication in the past, but it was nowhere to be found in the code... Anyway, it's there now.
