### ISSUE TITLE
Importing instruments over the tracker UI button assigns duplicate unit IDs

### ISSUE THREAD

**Issue by LeStahL** [vsariola/sointu#146]
When exporting instruments over the "Save Instrument" button in the tracker and re-importing them using the "Load Instrument" button, the same unit IDs like in the instrument file are used for its units, regardless of whether or not those units already exist in the patch.

**Comment by vsariola** [comment]
Damn. Must fix soon, this is where they come from.

**Comment by vsariola** [comment]
Ok, I firstly assign IDs when loading an instrument and I also made a paranoid thing: always check for ID collisions and if they somehow happen, automatically fix them by giving a completely new ID to the later unit(s) having same ID as the first one.

**Comment by LeStahL** [comment]
super cool, thanks for looking into this so quickly! :)
