### ISSUE TITLE
Exception in native tracker when deleting all instruments

### ISSUE THREAD

**Issue by LeStahL** [vsariola/sointu#148]
When running the native tracker and deleting all instruments, the tracker hard-crashes with the output attached.
[sointu_crashlog.log](https://github.com/user-attachments/files/17016184/sointu_crashlog.log)
I reproduce using 2b38e11643327ade28e50b83e7699a3670e79fd4 (Which is the current master).

**Comment by LeStahL** [comment]
The same happens in the native plugin (the crash even takes FL Studio down as well).

**Comment by vsariola** [comment]
Confirmed and fixed. The native VM was not that happy when a patch with 0 voices arrived (the Go VM handled it just fine).

**Comment by LeStahL** [comment]
wohoo, that was fast again! thanks! <3
