### ISSUE TITLE
Some keyboard shortcuts do not work as they should in tracker

### ISSUE THREAD

**Issue by bsh-hub** [vsariola/sointu#151]
Tested version v0.4.1.

- Pressing F8 does not stop playing anymore (F6 starts and stops playing)
- Pressing space do not start/stop playing if certain UI buttons are selected, instead it "clicks" the UI button

For example if I have just added (or removed) a track. The corresponding button is focused and pressing space presses the focused button (for example the plus sign and adds a new track). 

In the screenshot below I have added a track and then tried to start playback by pressing space. Instead a new track is added every time space is pressed.

![image](https://github.com/user-attachments/assets/3a4587ce-ab36-4d1e-b903-2394a2eddeba)

**Comment by vsariola** [comment]
1) F5-F8 was changed to match the order and function of the buttons in the row here:

![image](https://github.com/user-attachments/assets/2313d7e3-6731-4a86-a148-ce8982b6486c)

Is there a particular reason why F6 cannot be used?

2) The Gioui buttons have a bad habit of "capturing" focus, and they have defined space to mean click. ATM there is no way to prevent this, as far as I know; I contacted gioui authors about it and they did welcome the idea that there probably should be buttons that never gain focus, but basically the message was "pull requests welcome" :) Aaanyway, I could in principle roll my own widgets entirely, the total code of the buttons is just 500 lines or so, and without worrying about focus, could be even less:

https://github.com/gioui/gio/blob/main/widget/button.go
https://github.com/gioui/gio/blob/main/widget/material/button.go

**Comment by bsh-hub** [comment]
1. I have used F8 for stopping playback since Scream Tracker 3 (then Impulse Tracker, OpenMPT etc). When Sointu had the same shortcuts (start playback with F5 and stop playback with F8) I was pleasantly surprised. For this old dog getting used to press F6 for start and stop requires some unlearning... :) But otherwise using F6 for both is fine. User configurable shortcuts (with ini file or something) would be great but that is probably another discussion. Using space for start and stop is also something what I have used in other software. So that works also but has those other problems as discussed in second (2) problem.
2. Ok. Then it requires more work. As as workaround I have found that using mouse to click somewhere, what is not clickable by space, the sapce then works for start/stop playback correctly. Probably sometimes keeping the focus in the button is a desired functionality. For example if you are trying to use the interface completely only with the keyboard.

**Comment by vsariola** [comment]
I can change the shortcuts back, I'll figure out other keyboard short cuts for the remaining functionalities

**Comment by vsariola** [comment]
Actually, do you remember off the top your head the usual mranings of F5-F8 in the aforementioned trackers? Are there differences? What did the modifiers (Ctrl+F5 etc.) do?

**Comment by bsh-hub** [comment]
I don't directly remember those but Schism Tracker is a quite direct clone of Impulse Tracker so its shortcuts should match to those of ST3 and IT.

Schism Tracker in app help (shows when F1 is pressed) describes the shortcuts as follows:

![image](https://github.com/user-attachments/assets/d88c01a6-f34f-42c8-b112-d4f2d70b93c8)

(https://github.com/schismtracker/schismtracker)

OpenMPT has a bit different approach (the shortcuts are user configurable there and instead of defaults I have used somewhat IT compatible premade layout). OpenMPT documentation describes the default shortcuts like this:

![image](https://github.com/user-attachments/assets/d41d888f-21a2-4f34-a7e8-972db1a5efe1)

(https://wiki.openmpt.org/Manual:_Keyboard_Actions)

**Comment by esaruoho** [comment]
F6 is expected to start playback of loop, and another press to restart the playback. If pressing f6 again then 
It is definitely a plus if F8 stops playback properly.. in some trackers, F8 stops playback, and pressing F8 again will actually silence all the tail effects (reverbs, delays) acting as a panic / fullstop.

**Comment by vsariola** [comment]
|Button|SC3|OpenMPT|Proposal for Sointu|
|-|-|-|-|
| F5 | Play Information / Play Song | Play Song / Pause Song | Play from current cursor / Pause, same as space |
| Ctrl-F5 | Play Song | | Play song from start / Pause |
| F6 | Play current pattern | Play song from start | Set the current selection as loop and start playing it |
| Ctrl-F6 | | Play song from cursor | Play song from loop start (works like normal F6 if loop is not set i.e. sets a loop first) |
| F8 | Stop Playback | Pause Song | Stop Playback, or reset synth if already stopped |

Further proposal: all the play commands can be issued with Shift to indicate that playing should be done without the edit cursor following the playback cursor.

Or vice versa? If you hit only space or F5 without Shift, would you expect the edit cursor to start tracking the playback cursor?

**Comment by bsh-hub** [comment]
Sounds good to me. For me the default probably should be to not to follow the playback cursor. So pressing with shift would be to follow the cursor.

In OpenMPT there is a separate song wide checkbox field for follow song and the cursor will follow playback when it is checked.

**Comment by vsariola** [comment]
Just a little heads up that the latest master has the keybindings defined so that they resemble (again) the old trackers AND you can now override them as you please, by making a copy of [keybindings.yaml](https://raw.githubusercontent.com/vsariola/sointu/refs/heads/master/tracker/gioui/keybindings.yaml) to the Sointu configuration directory i.e.   `os.UserConfigDir()/sointu/keybindings.yaml`. On Windows, that directory is `AppData/Roaming/Sointu`. See [here](https://pkg.go.dev/os#UserConfigDir) how to find os.UserConfigDir() on other platforms.
