### ISSUE TITLE
MIDI Channel identification

### ISSUE THREAD

**Issue by wayfu** [vsariola/sointu#154]
It would be good if instruments could show with a number which midi channel they're controlled by somewhere.

**Comment by vsariola** [comment]
Question: would it be better to refer to them as 1-16 or 0-15? I've seen 1-16 in many places, but in the MIDI messages, the first channel is identified by integer value 0.

**Comment by LeStahL** [comment]
I think most DAWs display MIDI channels starting with Channel 1
