### ISSUE TITLE
Mechanism to play gm.dls based instruments in non-native tracker on linux

### ISSUE THREAD

**Issue by LeStahL** [vsariola/sointu#159]
When working on a prod targeting windows with gm.dls use, it's not possible to play back the track on linux.

Maybe Sointu could allow to specify where the non-native tracker & plugin look for gm.dls over a CLI arg and a menu entry? That way it would be possible to at least play and convert to wave correctly on linux (by copying the file over from windows).

**Comment by LeStahL** [comment]
(This would make cross-development much easier)

**Comment by vsariola** [comment]
I think it looks first for it from the current directory, if by any magic you get hold of this file on linux ;)

https://github.com/vsariola/sointu/blob/8fd2df19a16d16a7846a7ec02fb33e0422339b43/vm/go_synth.go#L80

**Comment by vsariola** [comment]
Is this not enough?

**Comment by LeStahL** [comment]
oh, even better - I'll try that :) didn't look into the source

**Comment by LeStahL** [comment]
works perfectly. Thank you! :)
