### ISSUE TITLE
Duplicate keyboard assignments

### ISSUE THREAD

**Issue by LeStahL** [vsariola/sointu#162]
Some keyboard shortcuts interfere with other features:

When typing hex in the tracker, it's impossible to enter values containing `a`, `1` or `0`. Those can still be achieved by entering the nearest hex value that is possible to enter and then clicking the increment button, this is painful however.

**Comment by LeStahL** [comment]
This seems to be a problem for `F`, `4` and `8` now with default key bindings.

**Comment by vsariola** [comment]
I fixed this last week and then broke it again this week 😭

**Comment by LeStahL** [comment]
happens. If we're really annoyed by UI regressions, we could find out if gioui is test-/mock-friendly :) but I think "checking from time to time if everything still works" is also a good strategy

**Comment by LeStahL** [comment]
it looks test-friendly from what I can tell by inspecting their own tests: https://github.com/gioui/gio/blob/main/widget/editor_test.go

**Comment by vsariola** [comment]
Yeah gioui being mostly stateless imgui it makes testing a real possibility. I really should do that. But the tests need to be carefully decided as I don't want minor pixel adjustments to cause tests to fail.
