### ISSUE TITLE
highpassfilter to delay

### ISSUE THREAD

**Issue by esaruoho** [vsariola/sointu#18]
would be good to have a highpass filter on delay

**Comment by vsariola** [comment]
You mean low pass filter, right? To make high pitch sounds decay away faster than low pitch sounds? It already has this low-pass filter: it is the damp parameter. 0 = no filtering, 128 = nothing gets through even in the first echo.

If you actually meant high pass filter, what's the audio use case?

It's possible to hack one together from the current units: make a full wet delay with no feedback, highpass filter it, send it to a receive unit earlier, add to the dry signal & feedback to the delay.

WIth these thoughts, do you still think we need one?

**Comment by esaruoho** [comment]
@vsariola  usecase for HP is, as always, get rid of low frequencies like <130hz which muddy up the sound.

**Comment by vsariola** [comment]
What's wrong with adding a high pass filter just before the delay / reverb? The general idea in Sointu is that units are limited in their functionality, and it's more like a modular synthesizer where you build the patch just the way you like it. This is also to keep the code size down: the small units are highly reusable and can be implemented with only a few bytes of assembly.

**Comment by esaruoho** [comment]
understood, closing
