### ISSUE TITLE
editmode_on / off control

### ISSUE THREAD

**Issue by esaruoho** [vsariola/sointu#19]
would be good to be able to keyjazz without inputting it to the pattern.

**Comment by vsariola** [comment]
you can do this when the cursor is in the instrument panel, is that enough? In Renoise, I remember getting tripped by the editmode being on or off; I always forgot it off and wondered why there are no notes entered at the cursor. I would prefer to have as little as possible state in the GUI, so the user does not get lost what state he/she is currently in

**Comment by esaruoho** [comment]
ok, closing
