### ISSUE TITLE
Adding Voices in tracker does not add more "channels"

### ISSUE THREAD

**Issue by esaruoho** [vsariola/sointu#3]
Steps to replicate:
1. Launch app
2. Click on -> on Voices to go from 1 to 5
3. Click on <- on Voices to go from 5 to 1

Expected: More tracks added to tracker view when going from 1...5, track count reduced in tracker when 5...1
Current: Nothing happens
![2021-02-15 11 52 19](https://user-images.githubusercontent.com/4966687/107930942-548fab80-6f84-11eb-9265-c67e039bcac2.gif)

**Comment by vsariola** [comment]
This is not what Voices means. These voices mean how many voices that one track is triggering. Typically, this would be 1 or 2. 2 would mean that when a new note comes, the other voice is always released *but keeps on playing with the envelopes releasing*.  With only one voice, if a new note comes before the envelopes have had time to ramp down, there will be nasty click.

What you expected to happen can be achieved by adding more voices to one instrument and then clicking add track to add more tracks that trigger voices of that one instrument.

This will probably trip more than one musician, so good documentation explaining the difference between voice, (polyphonic) instrument and (polyphonic) track is probably needed.

**Comment by esaruoho** [comment]
understood, closing
