### ISSUE TITLE
please add +12 -12 buttons on right of oscillator transpose

### ISSUE THREAD

**Issue by esaruoho** [vsariola/sointu#37]
<img width="542" alt="Screenshot 2021-02-17 at 10 24 29" src="https://user-images.githubusercontent.com/4966687/108176179-55524a00-710a-11eb-8ce3-3b063792f192.png">
 -

**Comment by vsariola** [comment]
There's a long plan to make specialized guis for every unit (or the most important ones at least). For example, filter could show the spectrum of the filter; oscillator could show wave form etc. This'll probably have to wait until I have a plan for implementing the unit specific GUIs
