### ISSUE TITLE
Method to toggle Pattern Playback Follow on/off

### ISSUE THREAD

**Issue by esaruoho** [vsariola/sointu#4]
I would prefer to be able to select if Pattern Playback Follow is on or not -- so I can continue tracking even with the song playing.

**Comment by vsariola** [comment]
If you move your cursor up and down, it ceases to follow the play position. Is this enough? Again, we could make a button to toggle "follow on/off" but this would be yet another toggle in the GUI to remember to click/unclick.

How about just ctrl-Space or something like that to start playing without the note tracking on?

**Comment by vsariola** [comment]
I pushed Ctrl-Space and F5-F7 key commands to play different ways. Ctrl-Space starts without notetracking; F5 plays from current pos & notetracking on, F6 plays from current pos with notetracking on and F7 continues wherever it was when it last stopped.

**Comment by esaruoho** [comment]
thanks, this solves a lot. closing.
