### ISSUE TITLE
3 osc = mac stops playing and never resumes until restarting app

### ISSUE THREAD

**Issue by esaruoho** [vsariola/sointu#41]
Steps to replicate:
on a M1 Mac, I add Oscs until I have 3 Oscs in the song.

Expected result: 3 Oscs play, or anything plays
Current result: 3 Oscs? Bye, nothing plays. Not even after pressing panic. Not even after removing the 2 Oscs and pressing panic. Just gone. Copy Song, Paste Song to new sointu-session, if 2 oscs = they play, if more than 2, silence.

**Comment by vsariola** [comment]
One day, there will be pure go implementation of the core, which will make the tracker ultra portable. Hopefully, this will fix all issues with M1 and other non-x86 platforms.

**Comment by vsariola** [comment]
That day is now. Please test and report if the new pure-Go core is more reliable. You should be able to run the whole thing without any x86 emulation.

**Comment by esaruoho** [comment]
closing, works better. thanks!
