### ISSUE TITLE
after adding instrument data, pressing cursor-right crashed 

### ISSUE THREAD

**Issue by esaruoho** [vsariola/sointu#42]
panic: runtime error: index out of range [1] with length 1

goroutine 34 [running]:
github.com/vsariola/sointu/tracker.(*Tracker).GetUnitParam(...)
	/Users/esaruoho/work/sointu/tracker/tracker.go:555
github.com/vsariola/sointu/tracker.(*Tracker).KeyEvent(0xc00009c800, 0xc00009c000, 0x43be02b, 0x3, 0x0, 0x4000000040000000)
	/Users/esaruoho/work/sointu/tracker/keyevent.go:335 +0x227c
github.com/vsariola/sointu/tracker.(*Tracker).Run(0xc00009c800, 0xc00009c000, 0x444f540, 0x4b69ea0)
	/Users/esaruoho/work/sointu/tracker/run.go:23 +0x3ba
main.main.func1(0xc00000e8c0)
	/Users/esaruoho/work/sointu/cmd/sointu-track/main.go:29 +0x136
created by main.main
	/Users/esaruoho/work/sointu/cmd/sointu-track/main.go:22 +0xe5
exit status 2

**Comment by vsariola** [comment]
This hopefully was fixed by the megarefactoring, but in case you get panics / crashes, remember to save the error messages / stack traces so I'll keep squashing buga

**Comment by vsariola** [comment]
I'm closing this for now, as I think it went away with the big work I did with the GUI model. Open new issues if you still find crashes.
