### ISSUE TITLE
need a visual way of seeing which instruments are playing at the top (instrument+global tab)

### ISSUE THREAD

**Issue by esaruoho** [vsariola/sointu#44]
is it possible to flash the instruments that are being triggered, at the topbar?
<img width="539" alt="Screenshot 2021-03-04 at 8 57 19" src="https://user-images.githubusercontent.com/4966687/109923580-a1cf8500-7cc7-11eb-8b68-19f52bb2d0de.png">

it'd really help with figuring out what is playing and where, or if anything is playing.

**Comment by vsariola** [comment]
It is and will definitely do. Also, once we have scopes, it will hopefully also be easier to follow which instruments are doing what.
