### ISSUE TITLE
send discrete note offs to halt "infinite notes"

### ISSUE THREAD

**Issue by esaruoho** [vsariola/sointu#45]
need a method to send discrete note offs to the whole soundspace and all instruments, without needing to press panic to kill sound

**Comment by vsariola** [comment]
We could note off all notes when play is started; that could lead to some issues though? One thing comes to my mind is that if one uses effects e.g. pitch ups, fades etc. with the assumption that they are left in on state for long periods of time, starting the play would kill those.

There's the "hex" boolean to denote effect tracks, perhaps we have F9 to release all non-hex tracks and F10 to release all tracks or smthing like that.
