### ISSUE TITLE
autoassign 0 to orderlist when adding a new track

### ISSUE THREAD

**Issue by esaruoho** [vsariola/sointu#47]
when adding a new track, please autoassign 0 to each row when adding a new track

**Comment by vsariola** [comment]
Do you mean just one 0 and rest empty in the order list or all patterns as 0? Majority of my tracks are usually empty, so I thought defaulting to all empty was the most appropriate thing to do

**Comment by esaruoho** [comment]
just one 0, rest empty.

**Comment by vsariola** [comment]
how about we just automagically add new patterns to the order list if user inputs notes to empty area? this is basically what you suggested here #53, so wouldn't that make adding the 0 pattern unnecessary?

**Comment by esaruoho** [comment]
yep, #53 solves this. closing.
