### ISSUE TITLE
improve orderlist visualization when adding new tracks - currently no way to see that there's unassigned orderlist tracks

### ISSUE THREAD

**Issue by esaruoho** [vsariola/sointu#48]
currently it feels like there's no way to really see that there's an unassigned orderlist column. maybe they could have `-` or something? 

<img width="192" alt="Screenshot 2021-03-04 at 9 00 02" src="https://user-images.githubusercontent.com/4966687/109923815-038fef00-7cc8-11eb-96b2-7dbbcba76660.png">
impr

**Comment by vsariola** [comment]
There definitely should be titles for those columns, maybe the presence of a title does the trick? Or a faint excel like empty cell?

**Comment by esaruoho** [comment]
some sort of empty cell instead of "empty space" :)

**Comment by vsariola** [comment]
I just pushed a version of this, please test if ok.

**Comment by esaruoho** [comment]
much better! closing.
