### ISSUE TITLE
Prompt "Are You Sure" when pressing Trashcan

### ISSUE THREAD

**Issue by esaruoho** [vsariola/sointu#5]
If I press Trashcan here or here, I never get prompted Are You sure. Would be good to prompt before deleting, as it is very heavily destructive
![image](https://user-images.githubusercontent.com/4966687/107931336-c49e3180-6f84-11eb-8573-62d39f8204ce.png)

**Comment by vsariola** [comment]
I agree that one rarely wants to delete an entire instrument, but units get deleted often, so clicking yes for every delete would be pretty bad. Both actions can be cancelled with Undo / Ctrl-Z.

Would it be enough to have confirmation only for deleting an instrument?

**Comment by esaruoho** [comment]
Delete instrument confirmation would be enough for sure

**Comment by esaruoho** [comment]
is this easy to implement?

**Comment by vsariola** [comment]
Not as easy as I would want; the GUI toolkit does not have "dialogs" so I have to construct one myself (add buttons & text etc.) Will implement as soon as I can.
