### ISSUE TITLE
Add Oscillator to Global -> auto-set LFO setting

### ISSUE THREAD

**Issue by esaruoho** [vsariola/sointu#52]
set LFO setting by default when Oscillator is added to Global

**Comment by vsariola** [comment]
Global is just an instrument named Global, what's the heuristic to know when to do this? The name? What if the user renames Global? Could there be a situation where a user configures two global instruments and calls them Global1 and Global2?

So far there's no special treatment of the Global in the code, so I'm bit on the edge if we should add any.

**Comment by esaruoho** [comment]
ok, closing
