### ISSUE TITLE
hung notes on pattern 1

### ISSUE THREAD

**Issue by esaruoho** [vsariola/sointu#54]
not sure why pattern1 is considered "..." instead of "---".
how do i create "---" ?

<img width="612" alt="Screenshot 2021-03-11 at 10 31 09" src="https://user-images.githubusercontent.com/4966687/110758221-effb0000-8254-11eb-897d-a1a05764cfc6.png">

**Comment by vsariola** [comment]
Pressing "A" creates a note off.  When creating a new track, Sointu unnecessarily initialized pattern 0 with note offs. I've just pushed a commit removing this.

The reason for this is that internally, 0 = note off and 1 = hold. I should probably make 0 = hold as that's the default "empty" one would expect, but the reason why it is now like this is historical: this is the 4klang player stores them.
