### ISSUE TITLE
capslock and § could also introduce note off

### ISSUE THREAD

**Issue by esaruoho** [vsariola/sointu#57]
pressing § (right left of 1) could be note off and so could capslock

**Comment by vsariola** [comment]
I checked  §: it gives the same character code on Windows that was the correct character code to use for octave up and down on Mac. So it cannot be redefined without braking the octave up / down shortcut on Mac. Also, we don't get capslock keyevents from gioui (the gui toolkit we use), so we cannot bind anything to capslock.

I'm closing as gioui does not make this possible. Unfortunately, we will have to live with "a" and "1" binded for note-offs for the moment.
