### ISSUE TITLE
Fix denormalizing

### ISSUE THREAD

**Issue by vsariola** [vsariola/sointu#68]
Despite all attempts, there seems to be something denormalizing, exemplified by the Adam song. When the kick stops playing, the audio starts to stutter after a while. This happens with the x87 core.

Need to investigate why this is still happening and how to avoid it.

**Comment by reaby** [comment]
i tried to debug this... got cpu usage pretty high with only one simple patch: env+osc+mulp+filter+filter+pan+outaux.
with my system from default 5% cpu usage, it gets to 12.9% with only this, increasing sound to 4 it already is at 24%.

**Comment by vsariola** [comment]
I'm pretty sure it's the filter unit. Let's see if I can spot where we need flush to zero.

**Comment by LeStahL** [comment]
I can reproduce it in tracks with filter unit on 3-oscilator instrument with unison enabled, and it vanishes when removing the filter.

**Comment by LeStahL** [comment]
Envelope + Send to filter cutoff makes it significantly worse.

**Comment by vsariola** [comment]
Ok, I think I found the right place to flush to zero, can you try the binaries from the dev branch (https://github.com/vsariola/sointu/actions/runs/9584723750) to see if that fixes the CPU hogging.

**Comment by LeStahL** [comment]
Checked; this fixes the CPU hogging, thank you very much for looking into this! :)

**Comment by vsariola** [comment]
Great! I'll merge this to master branch then.
