### ISSUE TITLE
How to use the gui ? 

### ISSUE THREAD

**Issue by gedw99** [vsariola/sointu#85]
Love this project, and want to extend it.

But i honestly can not work out how to make the GUI play the music sequence that is loaded.

I watched the video and cant quite see what your pressing to make it work.
https://www.youtube.com/watch?v=fokSSaz3mbs

**Comment by vsariola** [comment]
Sorry, this issue slipped my attention; I'm in summer mode so hobby development is smaller. Try F5-F8 keys or hitting space? Is this what you are after?

**Comment by vsariola** [comment]
Closing this as this is probably not relevant anymore.
