### ISSUE TITLE
Keyboard layout for playing notes is always EN

### ISSUE THREAD

**Issue by LeStahL** [vsariola/sointu#94]
Keyboard layout for playing midi notes with the keyboard in Sointu is always EN, regardless of the layout selected in the OS. Verified this behavior on windows using sointu-tracker and sointu-vsti 9db6ecb3dafad09f473743748ea17c9019631be8.

When typing slot type names in the stack editor, the layout seems to be correct however.

Not a big issue, as using the synth with a midi controller is more effective anyways :)

**Comment by vsariola** [comment]
Gioui is responsible for the keyboard input. I need to dig into gioui how to make it respect the keyboard layout (we may need to patch gioui, not sointu).

**Comment by vsariola** [comment]
Just a little heads up that in the latest master you can now override the keybindings as you please, by making a copy of [keybindings.yaml](https://raw.githubusercontent.com/vsariola/sointu/refs/heads/master/tracker/gioui/keybindings.yaml) to the Sointu configuration directory i.e. `os.UserConfigDir()/sointu/keybindings.yaml`. On Windows, that directory is `AppData/Roaming/Sointu`. See [here](https://pkg.go.dev/os#UserConfigDir) how to find os.UserConfigDir() on other platforms.

I think this solves the bad keyboard layout issue, as you can just remap all the note buttons however you like.

**Comment by vsariola** [comment]
Still a little change: the user-defined keybindings.yml just documents *changes* from the default keybindings.yml. So, if swapping A <-> Z is the only thing you need, you can define just those two lines and let the default keybindings.yml define all the rest. A line with no `action:` means "unbind" the key.
