### ISSUE TITLE
VST Plugin crash when sending note to MIDI channel without instrument

### ISSUE THREAD

**Issue by LeStahL** [vsariola/sointu#98]
When sending notes to the VST plugin, if there is no instrument configured in Sointu with the channel of the note, the VST plugin will crash (along with FL Studio).
This happens on the current master 94926c55964cd302905a3754f5a6d920d24bb423 with FL Studio v20.9.2 build 2963.

Usually this happens when loading a project and forgetting to load the song in sointu as well :)

**Comment by vsariola** [comment]
Reproducible even in Renoise: just changing the channel to 3, which is not the default instrument or global it crashes. Investigating.

**Comment by vsariola** [comment]
The issue might be fixed; can you check if the issue persists with the binaries here: https://github.com/vsariola/sointu/suites/15527937184/artifacts/886368462

**Comment by LeStahL** [comment]
tested; fixed :)

**Comment by vsariola** [comment]
Thanks :)(: closing
