### ISSUE TITLE
File->Save Song and CTRL+S do not save the song

### ISSUE THREAD

**Issue by LeStahL** [vsariola/sointu#99]
When opening a song file and pressing CTRL+S, or navigating to File->Save Song, the song is not actually saved.

I tested and reproduced this behavior in the tracker and the VST plugin on the current master 61776f397afc5f0af7c199f15774bea214c42085.

**Comment by vsariola** [comment]
The refactoring into using filesystem dialogs has obviously broken "some minor thing" :D Oops. Investigating.
